# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bff84a091282a2fb7c476d6e33247bdca8827dc28d65bde10e27fee993894fd6915cea0bb7ea92d02de678dc02019fe903108cb07033321bb73b998d3a1fd1ce

test:
  secret_key_base: 985206f6ec67c7cc09199651f3184e5c952dcfe3241c4a9b1335952725e35990490c8b22a2a9c7ab806f24b39cc9d67a54a7fb3adb41bb8b1cd5f9dc5cc10d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
